/**
 * packages/shared/src/abis/index.ts — ABI bridge for Bombe contracts. (T-406)
 *
 * AUTO-GENERATED by scripts/gen-abis.mjs — DO NOT EDIT BY HAND.
 * Regenerate: node scripts/gen-abis.mjs
 *
 * Exports typed ABI arrays as `as const` (viem-compatible) and
 * the DeploymentAddresses shape for on-chain address passing.
 */

import AgentAttestationAbiJson from "./AgentAttestation.abi.json" with { type: "json" };
import AgentRegistryAbiJson from "./AgentRegistry.abi.json" with { type: "json" };
import AgentSlashingAbiJson from "./AgentSlashing.abi.json" with { type: "json" };
import TuringLeaderboardAbiJson from "./TuringLeaderboard.abi.json" with { type: "json" };

// ---------------------------------------------------------------------------
// ABI exports (typed as const for viem)
// ---------------------------------------------------------------------------

export const AgentRegistryAbi = AgentRegistryAbiJson as typeof AgentRegistryAbiJson;
export const AgentAttestationAbi = AgentAttestationAbiJson as typeof AgentAttestationAbiJson;
export const AgentSlashingAbi = AgentSlashingAbiJson as typeof AgentSlashingAbiJson;
export const TuringLeaderboardAbi = TuringLeaderboardAbiJson as typeof TuringLeaderboardAbiJson;

// ---------------------------------------------------------------------------
// DeploymentAddresses — typed shape for on-chain deployment records
// ---------------------------------------------------------------------------

/**
 * DeploymentAddresses — the four deployed contract addresses for a Bombe
 * deployment (anvil local or live Mantle Sepolia).
 *
 * All fields are 0x-prefixed Ethereum address strings.
 */
export interface DeploymentAddresses {
  registry: `0x${string}`;
  attestation: `0x${string}`;
  slashing: `0x${string}`;
  leaderboard: `0x${string}`;
}
