/**
 * demo-data.ts — Typed getters for the deterministic demo-data layer.
 *
 * The data lives in apps/web/fixtures/demo-data.json, generated by
 * apps/web/scripts/gen-demo-data.test.ts. ALL hashes in that file were
 * produced by hashCanonical — never hand-typed (PRD §15.4 guardrail).
 *
 * This module exposes typed, null-safe getters used by /leaderboard and
 * /claim/[id] pages. NO `any` anywhere in this file.
 *
 * PRD §6.6 — web app pages; PRD §14.4 — verify-hash requirement.
 */

import type { Claim } from "@bombe/shared";
import rawData from "../fixtures/demo-data.json";

// ---------------------------------------------------------------------------
// Re-exported types (no `any`)
// ---------------------------------------------------------------------------

export type Decision = "VALID" | "REJECTED" | "ABSTAIN";

/** A single ReAct step in a trace. */
export type TraceStep = {
  step: number;
  thought: string;
  action: unknown;
  observation: unknown;
  ts: number;
  modelSwitched?: {
    modelSwitched: true;
    from: string;
    to: string;
    reason: string;
  };
};

/** The final decision block in a trace. */
export type TraceFinal = {
  decision: Decision;
  confidenceBps: number;
  rationaleSummary: string;
  reasons: string[];
};

/** A stored trace with its embedded reasoningHash. */
export type StoredTrace = {
  traceVersion: "1.0";
  agentId: string;
  claimId: string;
  steps: TraceStep[];
  final: TraceFinal;
  /** keccak256(canonicalJson(trace body)) — computed by generator, never hand-typed. */
  reasoningHash: `0x${string}`;
  /** Only present for Plugboard — epoch-0 skill document hash. */
  skillHash?: `0x${string}`;
};

/** An attestation record emitted by one agent for one claim. */
export type AttestationRecord = {
  agentId: string;
  claimId: string;
  decision: Decision;
  confidenceBps: number;
  reasoningHash: `0x${string}`;
  sourcesHash: `0x${string}`;
  traceURI: string;
  txHash: string;
  agentAddress: string;
  latencyMs: number;
  costUsd: number;
  isHuman: boolean;
  /** true only for Plugboard on claim D — hit JudgmentTierRequiresAbstain revert. */
  blockedByProtocol: boolean;
  skillHash: `0x${string}` | null;
};

/** A single row in the lifetime leaderboard. */
export type LeaderboardRow = {
  rank: number;
  agentId: string;
  isHuman: boolean;
  /** true for Plugboard — external runtime not written by Bombe's team. */
  isExternal: boolean;
  correct: number;
  wrong: number;
  abstained: number;
  totalDecisions: number;
  /** accuracy% excluding abstentions from denominator; null when all-abstain. */
  accuracyPct: number | null;
  abstentionPct: number;
  decisivenessPct: number;
  avgLatencyMs: number;
  totalCostUsd: number;
  bond: number;
  slashes: number;
  reputation: number;
};

// ---------------------------------------------------------------------------
// Narrow raw JSON to typed shapes
// ---------------------------------------------------------------------------
// JSON imports don't carry rich types, so we cast once here and validate shape.

type RawData = typeof rawData;

/** All four claim IDs. */
export type ClaimId = "A" | "B" | "C" | "D";

// ---------------------------------------------------------------------------
// Getters
// ---------------------------------------------------------------------------

/**
 * getClaims — returns all four demo claims in order A–D.
 */
export function getClaims(): Claim[] {
  return (rawData.claims as unknown[]).map((c) => c as Claim);
}

/**
 * getClaim — returns a single claim by ID, or undefined if not found.
 */
export function getClaim(id: string): Claim | undefined {
  return (rawData.claims as unknown[]).find((c) => (c as Claim).id === id) as Claim | undefined;
}

/**
 * getAttestations — returns all attestation records for a claim.
 * Returns [] for unknown claim IDs.
 */
export function getAttestations(claimId: string): AttestationRecord[] {
  const map = rawData.attestations as Record<string, unknown[]>;
  const list = map[claimId] ?? [];
  return list as AttestationRecord[];
}

/**
 * getTrace — returns the stored trace for (claimId, agentId).
 * Returns undefined if either is unknown.
 */
export function getTrace(claimId: string, agentId: string): StoredTrace | undefined {
  const tracesByAgent = (rawData.traces as Record<string, Record<string, unknown>>)[claimId];
  if (!tracesByAgent) return undefined;
  const trace = tracesByAgent[agentId];
  if (!trace) return undefined;
  return trace as StoredTrace;
}

/**
 * getLeaderboard — returns all leaderboard rows, pre-ranked by accuracy desc /
 * decisiveness desc. Humans and AIs are interleaved in one ranked table.
 * Plugboard gets isExternal=true (renders as "EXTERNAL RUNTIME" badge).
 */
export function getLeaderboard(): LeaderboardRow[] {
  return (rawData.leaderboard as unknown[]).map((r) => r as LeaderboardRow);
}

/**
 * getPlugboardSkillHash — the epoch-0 skill document hash.
 */
export function getPlugboardSkillHash(): `0x${string}` {
  return rawData.plugboardSkillHash as `0x${string}`;
}

/**
 * getAllAgentIds — canonical order for per-agent tabs on /claim/[id].
 */
export const ALL_AGENT_IDS = ["reflector", "rotor", "stator", "plugboard", "human"] as const;
export type AgentId = (typeof ALL_AGENT_IDS)[number];
