#!/usr/bin/env node
/**
 * gen-abis.mjs — ABI bridge generator for Bombe. (T-406)
 *
 * Reads forge artifacts from contracts/out/<Contract>.sol/<Contract>.json
 * and writes:
 *   packages/shared/src/abis/AgentRegistry.abi.json
 *   packages/shared/src/abis/AgentAttestation.abi.json
 *   packages/shared/src/abis/AgentSlashing.abi.json
 *   packages/shared/src/abis/TuringLeaderboard.abi.json
 *   packages/shared/src/abis/index.ts  (typed TS consts + DeploymentAddresses type)
 *
 * Run: node scripts/gen-abis.mjs
 * Also wired as pnpm gen:abis in root package.json.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");

const contracts = ["AgentRegistry", "AgentAttestation", "AgentSlashing", "TuringLeaderboard"];

const outDir = resolve(repoRoot, "packages/shared/src/abis");
mkdirSync(outDir, { recursive: true });

/** @type {Record<string, unknown[]>} */
const abis = {};

for (const name of contracts) {
  const artifactPath = resolve(repoRoot, `contracts/out/${name}.sol/${name}.json`);
  const artifact = JSON.parse(readFileSync(artifactPath, "utf-8"));
  const abi = artifact.abi;
  abis[name] = abi;

  // Write raw JSON ABI file.
  const jsonPath = resolve(outDir, `${name}.abi.json`);
  writeFileSync(jsonPath, `${JSON.stringify(abi, null, 2)}\n`);
  console.log(`Wrote ${jsonPath}`);
}

// Write TypeScript index with typed const exports and DeploymentAddresses type.
const tsContent = `/**
 * packages/shared/src/abis/index.ts — ABI bridge for Bombe contracts. (T-406)
 *
 * AUTO-GENERATED by scripts/gen-abis.mjs — DO NOT EDIT BY HAND.
 * Regenerate: node scripts/gen-abis.mjs
 *
 * Exports typed ABI arrays as \`as const\` (viem-compatible) and
 * the DeploymentAddresses shape for on-chain address passing.
 */

import AgentRegistryAbiJson from "./AgentRegistry.abi.json" with { type: "json" };
import AgentAttestationAbiJson from "./AgentAttestation.abi.json" with { type: "json" };
import AgentSlashingAbiJson from "./AgentSlashing.abi.json" with { type: "json" };
import TuringLeaderboardAbiJson from "./TuringLeaderboard.abi.json" with { type: "json" };

// ---------------------------------------------------------------------------
// ABI exports (typed as const for viem)
// ---------------------------------------------------------------------------

export const AgentRegistryAbi = AgentRegistryAbiJson as typeof AgentRegistryAbiJson;
export const AgentAttestationAbi = AgentAttestationAbiJson as typeof AgentAttestationAbiJson;
export const AgentSlashingAbi = AgentSlashingAbiJson as typeof AgentSlashingAbiJson;
export const TuringLeaderboardAbi = TuringLeaderboardAbiJson as typeof TuringLeaderboardAbiJson;

// ---------------------------------------------------------------------------
// DeploymentAddresses — typed shape for on-chain deployment records
// ---------------------------------------------------------------------------

/**
 * DeploymentAddresses — the four deployed contract addresses for a Bombe
 * deployment (anvil local or live Mantle Sepolia).
 *
 * All fields are 0x-prefixed Ethereum address strings.
 */
export interface DeploymentAddresses {
  registry: \`0x\${string}\`;
  attestation: \`0x\${string}\`;
  slashing: \`0x\${string}\`;
  leaderboard: \`0x\${string}\`;
}
`;

const tsPath = resolve(outDir, "index.ts");
writeFileSync(tsPath, tsContent);
console.log(`Wrote ${tsPath}`);

console.log("gen-abis: done.");
